### ISSUE TITLE
not working in csgo

### ISSUE THREAD

**Issue by panikajo** [hive365/SourceMod-Server-Plugin#1]
L 09/12/2023 - 12:38:15: [SM] Exception reported: Invalid Handle 0 (error 4)
L 09/12/2023 - 12:38:15: [SM] Blaming: hive365radio.smx
L 09/12/2023 - 12:38:15: [SM] Call stack trace:
L 09/12/2023 - 12:38:15: [SM]   [0] StringMap.GetValue
L 09/12/2023 - 12:38:15: [SM]   [1] Line 98, C:\Users\panikajo\Desktop\scripting\include\json\helpers\typedstringmap.inc::TypedStringMap.GetOptionalValue
L 09/12/2023 - 12:38:15: [SM]   [2] Line 151, C:\Users\panikajo\Desktop\scripting\include\json\helpers\typedstringmap.inc::TypedStringMap.GetHandle
L 09/12/2023 - 12:38:15: [SM]   [3] Line 71, C:\Users\panikajo\Desktop\scripting\include\json\helpers\metastringmap.inc::MetaStringMap.Data.get
L 09/12/2023 - 12:38:15: [SM]   [4] Line 139, C:\Users\panikajo\Desktop\scripting\include\json\helpers\metastringmap.inc::MetaStringMap.GetHandle
L 09/12/2023 - 12:38:15: [SM]   [5] Line 430, C:\Users\panikajo\Desktop\scripting\include\json\object.inc::JSON_Object.GetObject
L 09/12/2023 - 12:38:15: [SM]   [6] Line 663, C:\Users\panikajo\Desktop\scripting\hive365radio.sp::ParseSocketInfo
L 09/12/2023 - 12:38:15: [SM]   [7] Line 791, C:\Users\panikajo\Desktop\scripting\hive365radio.sp::OnSocketReceive

**Comment by Coolguy3289** [comment]
It's weird having the repo public, so I forget that pushing to master generally signals ready for use. I'm aware of this error, still working on a fix for it before publishing the new version on our downloads page. As for CS:GO Specifically, I have to check if it's compatible or not, last I checked the MOTD was still removed rendering the plugin's radio functions useless.

**Comment by Coolguy3289** [comment]
Try again with this latest commit @panikajo
